trigger:
- master

pool: 'UKHO Ubuntu 1804'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: $(dockerserviceconnection)
- script: |
    docker build -t ukhydrographicoffice/azdoexporter .
  displayName: 'Build exporter and image'
- script: |
    docker push ukhydrographicoffice/azdoexporter
  displayName: 'Docker push'

