trigger:
- master

pool: 'UKHO Ubuntu 1804'

steps:
- script: |
    docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.14 go build -v
    ls
  displayName: 'Get dependencies, then build'
