[servers]

    [servers.tfs]
    address = "http://tfs:8080/tfs"
	defaultCollection = "UKHO"

    [servers.ukhogov]
    address = "https://ukhogov.visualstudio.com"
    useProxy = true

    [servers.ukhocustomer]
    address = "https://ukhocustomer.visualstudio.com"
    useProxy = true

[proxy]
    url = "http://smoothwall.ukho.gov.uk:8080"